paths:
  fastq_raw:      "1_DATA/FASTQ"
  fastq_processed: "2_ANALYSES/Results/02_preprocessing"
  reference:      "1_DATA/REFERENCE"
  analyses:       "2_ANALYSES"

cluster:
  threads: 8
  memory: "32G"
  queue: "short"